/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.interfacetb;

import javax.swing.JOptionPane;

public class bebida extends javax.swing.JFrame {

    /**
     * Creates new form bebida
     */
    public bebida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipo_bebida = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sabor_bebida = new javax.swing.JComboBox<>();
        base_bebida = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tipo_na = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        tipo_s = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        area_bebida = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        salvar_bebida = new javax.swing.JButton();
        limpar_bebida = new javax.swing.JButton();
        nome_bebida = new javax.swing.JTextField();
        voltar_menu = new javax.swing.JButton();
        tipo_a = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(161, 146, 134));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\ADS\\interface_chicos_burguer\\interface_chicos-main\\img\\IconBurguerPNG_200x200-removebg-preview.png")); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, -1));

        sabor_bebida.setBackground(new java.awt.Color(255, 255, 255));
        sabor_bebida.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        sabor_bebida.setForeground(new java.awt.Color(0, 0, 0));
        sabor_bebida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Morango", "Limão", "Maracujá", "Cola", "Guaraná", "Laranja", "Uva" }));
        sabor_bebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sabor_bebidaActionPerformed(evt);
            }
        });
        jPanel2.add(sabor_bebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 74, 234, 30));

        base_bebida.setBackground(new java.awt.Color(255, 255, 255));
        base_bebida.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        base_bebida.setForeground(new java.awt.Color(0, 0, 0));
        base_bebida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Leite", "Leite Condensado", "Creme de Leite", "Água", "Vodka", "Tequila", "Cachcaça" }));
        base_bebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                base_bebidaActionPerformed(evt);
            }
        });
        jPanel2.add(base_bebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 165, 282, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Escolha o sabor!");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 40, -1, -1));
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Escolha a base!");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 131, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Tipo:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 134, -1, -1));

        tipo_bebida.add(tipo_na);
        tipo_na.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tipo_na.setForeground(new java.awt.Color(0, 0, 0));
        tipo_na.setText("Não alcólico");
        jPanel2.add(tipo_na, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Nome da Bebida!");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 42, -1, -1));

        tipo_bebida.add(tipo_s);
        tipo_s.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tipo_s.setForeground(new java.awt.Color(0, 0, 0));
        tipo_s.setText("Soda");
        jPanel2.add(tipo_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 170, -1, -1));

        area_bebida.setBackground(new java.awt.Color(255, 255, 255));
        area_bebida.setColumns(20);
        area_bebida.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        area_bebida.setForeground(new java.awt.Color(0, 0, 0));
        area_bebida.setRows(5);
        jScrollPane1.setViewportView(area_bebida);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 463, 135));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Nova Bebida:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, -1, 40));

        salvar_bebida.setBackground(new java.awt.Color(154, 88, 51));
        salvar_bebida.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        salvar_bebida.setForeground(new java.awt.Color(0, 0, 0));
        salvar_bebida.setText("Salvar");
        salvar_bebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar_bebidaActionPerformed(evt);
            }
        });
        jPanel2.add(salvar_bebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 185, 43));

        limpar_bebida.setBackground(new java.awt.Color(154, 88, 51));
        limpar_bebida.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        limpar_bebida.setForeground(new java.awt.Color(0, 0, 0));
        limpar_bebida.setText("Limpar");
        limpar_bebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpar_bebidaActionPerformed(evt);
            }
        });
        jPanel2.add(limpar_bebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 185, 42));

        nome_bebida.setBackground(new java.awt.Color(255, 255, 255));
        nome_bebida.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nome_bebida.setForeground(new java.awt.Color(0, 0, 0));
        nome_bebida.setText("Digite o nome da bebida");
        nome_bebida.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nome_bebidaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nome_bebidaFocusLost(evt);
            }
        });
        nome_bebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_bebidaActionPerformed(evt);
            }
        });
        jPanel2.add(nome_bebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 76, 282, -1));

        voltar_menu.setBackground(new java.awt.Color(154, 88, 51));
        voltar_menu.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        voltar_menu.setForeground(new java.awt.Color(0, 0, 0));
        voltar_menu.setText("« Voltar Produtos");
        voltar_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar_menuActionPerformed(evt);
            }
        });
        jPanel2.add(voltar_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, 43));

        tipo_bebida.add(tipo_a);
        tipo_a.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tipo_a.setForeground(new java.awt.Color(0, 0, 0));
        tipo_a.setText("Alcólico");
        jPanel2.add(tipo_a, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 929, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sabor_bebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sabor_bebidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sabor_bebidaActionPerformed

    private void base_bebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_base_bebidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_base_bebidaActionPerformed

    private void salvar_bebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar_bebidaActionPerformed
        // TODO add your handling code here:
        int valor = JOptionPane.showConfirmDialog(null,"Deseja salvar?","Opções", JOptionPane.YES_NO_CANCEL_OPTION);
        
        if(valor==0){
            bebidaOBJ beb = new bebidaOBJ();
            beb.setNome_bebida(nome_bebida.getText());
            beb.setBase_bebida((String)base_bebida.getSelectedItem());
            beb.setSabor_bebida((String)sabor_bebida.getSelectedItem());
            if(tipo_na.isSelected()){
                beb.setTipo_bebida("Não Alcólica");
            }else if(tipo_a.isSelected()){
                beb.setTipo_bebida("Bebida Alcólica");
            }else{
                beb.setTipo_bebida("Soda");
            }
            area_bebida.setText(beb.status_bebida());
        }else if(valor==2){
            System.exit(0);
        }
    }//GEN-LAST:event_salvar_bebidaActionPerformed

    private void voltar_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar_menuActionPerformed
        // TODO add your handling code here:
        dispose();
        new carregamento().setVisible(true);
    }//GEN-LAST:event_voltar_menuActionPerformed

    private void nome_bebidaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nome_bebidaFocusGained
        // TODO add your handling code here:
        if(nome_bebida.getText().equals("Digite o nome da bebida")){
            nome_bebida.setText("");
        }
        
    }//GEN-LAST:event_nome_bebidaFocusGained

    private void nome_bebidaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nome_bebidaFocusLost
        // TODO add your handling code here:
        if(nome_bebida.getText().equals("")){
            nome_bebida.setText("Digite o nome da bebida");
        }
    }//GEN-LAST:event_nome_bebidaFocusLost

    private void limpar_bebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpar_bebidaActionPerformed
        // TODO add your handling code here:
        nome_bebida.setText("");
        base_bebida.setSelectedIndex(0);
        tipo_na.setSelected(false);
        tipo_a.setSelected(false);
        tipo_s.setSelected(false);
        sabor_bebida.setSelectedIndex(0);
        area_bebida.setText("");
    }//GEN-LAST:event_limpar_bebidaActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        dispose();
        new inicio().setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void nome_bebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_bebidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_bebidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bebida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area_bebida;
    private javax.swing.JComboBox<String> base_bebida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpar_bebida;
    private javax.swing.JTextField nome_bebida;
    private javax.swing.JComboBox<String> sabor_bebida;
    private javax.swing.JButton salvar_bebida;
    private javax.swing.JRadioButton tipo_a;
    private javax.swing.ButtonGroup tipo_bebida;
    private javax.swing.JRadioButton tipo_na;
    private javax.swing.JRadioButton tipo_s;
    private javax.swing.JButton voltar_menu;
    // End of variables declaration//GEN-END:variables
}
