/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.interfacetb;

import javax.swing.JOptionPane;

public class funcionarios extends javax.swing.JFrame {

    /**
     * Creates new form funcionarios
     */
    public funcionarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        salvar_func = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        limpar_func = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        nome_func = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fem = new javax.swing.JRadioButton();
        masc = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cpf_func = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cargo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        uniforme = new javax.swing.JCheckBox();
        news = new javax.swing.JLabel();
        bene_n = new javax.swing.JRadioButton();
        bene_s = new javax.swing.JRadioButton();
        nb = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        area_func = new javax.swing.JTextArea();
        voltar_menu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(161, 146, 134));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Funcionários");

        salvar_func.setBackground(new java.awt.Color(154, 88, 51));
        salvar_func.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        salvar_func.setForeground(new java.awt.Color(0, 0, 0));
        salvar_func.setText("Salvar");
        salvar_func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar_funcActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Cadastre-se aqui!");

        limpar_func.setBackground(new java.awt.Color(154, 88, 51));
        limpar_func.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        limpar_func.setForeground(new java.awt.Color(0, 0, 0));
        limpar_func.setText("Limpar");
        limpar_func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpar_funcActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(154, 88, 51));

        nome_func.setBackground(new java.awt.Color(255, 255, 255));
        nome_func.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nome_func.setForeground(new java.awt.Color(0, 0, 0));
        nome_func.setText("Digite seu nome");
        nome_func.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nome_funcFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nome_funcFocusLost(evt);
            }
        });
        nome_func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_funcActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nome:");

        fem.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fem.setForeground(new java.awt.Color(0, 0, 0));
        fem.setText("Feminino");
        fem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femActionPerformed(evt);
            }
        });

        masc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        masc.setForeground(new java.awt.Color(0, 0, 0));
        masc.setText("Masculino");
        masc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mascActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Sexo:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("CPF");

        cpf_func.setBackground(new java.awt.Color(255, 255, 255));
        cpf_func.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cpf_func.setForeground(new java.awt.Color(0, 0, 0));
        cpf_func.setText("Digite seu CPF");
        cpf_func.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cpf_funcFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cpf_funcFocusLost(evt);
            }
        });
        cpf_func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpf_funcActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Setor:");

        cargo.setBackground(new java.awt.Color(255, 255, 255));
        cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "T.I.", "Financeiro", "Cozinha", "Entrega", "Logistica", "Direção" }));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Deseja receber o uniforme?");

        uniforme.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        uniforme.setForeground(new java.awt.Color(0, 0, 0));
        uniforme.setText("Sim");
        uniforme.setToolTipText("");
        uniforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uniformeActionPerformed(evt);
            }
        });

        news.setBackground(new java.awt.Color(255, 255, 255));
        news.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        news.setForeground(new java.awt.Color(0, 0, 0));
        news.setText("Deseja receber VA+VT?");

        bene_n.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bene_n.setForeground(new java.awt.Color(0, 0, 0));
        bene_n.setText("Não");
        bene_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bene_nActionPerformed(evt);
            }
        });

        bene_s.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bene_s.setForeground(new java.awt.Color(0, 0, 0));
        bene_s.setText("Sim");
        bene_s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bene_sActionPerformed(evt);
            }
        });

        nb.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nb.setForeground(new java.awt.Color(0, 0, 0));
        nb.setText("Não-Binário");
        nb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(news)
                        .addGap(14, 14, 14)
                        .addComponent(bene_s)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bene_n))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(uniforme))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(11, 11, 11))
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nome_func, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                            .addComponent(cpf_func, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(masc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nb)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome_func, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fem)
                    .addComponent(masc)
                    .addComponent(jLabel3)
                    .addComponent(nb, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cpf_func, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(uniforme))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(news)
                    .addComponent(bene_n)
                    .addComponent(bene_s))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\ADS\\interface_chicos_burguer\\interface_chicos-main\\img\\IconBurguerPNG_200x200-removebg-preview.png")); // NOI18N

        area_func.setColumns(20);
        area_func.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        area_func.setRows(5);
        jScrollPane2.setViewportView(area_func);

        voltar_menu.setBackground(new java.awt.Color(154, 88, 51));
        voltar_menu.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        voltar_menu.setForeground(new java.awt.Color(0, 0, 0));
        voltar_menu.setText("« Voltar Menu");
        voltar_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar_menuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(limpar_func, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(salvar_func, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(voltar_menu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel1)))
                        .addGap(10, 10, 10)
                        .addComponent(salvar_func, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(limpar_func, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(voltar_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane2))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(90, 90, 90)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvar_funcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar_funcActionPerformed
        // TODO add your handling code here:
        int valor = JOptionPane.showConfirmDialog(null,"Deseja salvar?","Opções",JOptionPane.YES_NO_CANCEL_OPTION);
        
        if(valor==0){
            funcionariosOBJ func = new funcionariosOBJ();
            func.setNome_func(nome_func.getText());
            func.setCpf(cpf_func.getText());
            func.setCargo((String)cargo.getSelectedItem());
            func.setUniforme(uniforme.isSelected()?"Sim":"Não");
            if(bene_s.isSelected()){
                func.setVt("Sim");
            }else{
                func.setVt("Não");
            }
            if(masc.isSelected()){
                func.setSexo_func("Masculino");
            }else if(fem.isSelected()){
                func.setSexo_func("Feminino");
            }else{
                func.setSexo_func("Não-binário");
            }
            area_func.setText(func.status_func());
        }else if(valor==2){
            System.exit(0);
        }
    }//GEN-LAST:event_salvar_funcActionPerformed

    private void limpar_funcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpar_funcActionPerformed
        // TODO add your handling code here:
        nome_func.setText("");
        masc.setSelected(false);
        fem.setSelected(false);
        nb.setSelected(false);
        cpf_func.setText("");
        cargo.setSelectedIndex(0);
        uniforme.setSelected(false);
        bene_s.setSelected(false);
        bene_n.setSelected(false);
    }//GEN-LAST:event_limpar_funcActionPerformed

    private void nome_funcFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nome_funcFocusGained
        // TODO add your handling code here:
        if(nome_func.getText().equals("Digite seu nome")){
            nome_func.setText("");
        }
    }//GEN-LAST:event_nome_funcFocusGained

    private void nome_funcFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nome_funcFocusLost
        // TODO add your handling code here:
        if(nome_func.getText().equals("")){
            nome_func.setText("Digite seu nome");
        }
    }//GEN-LAST:event_nome_funcFocusLost

    private void nome_funcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_funcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_funcActionPerformed

    private void femActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femActionPerformed
        // TODO add your handling code here:
        masc.setSelected(false);
        nb.setSelected(false);
    }//GEN-LAST:event_femActionPerformed

    private void mascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mascActionPerformed
        // TODO add your handling code here:
        fem.setSelected(false);
        nb.setSelected(false);
    }//GEN-LAST:event_mascActionPerformed

    private void cpf_funcFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpf_funcFocusGained
        // TODO add your handling code here:
        if(cpf_func.getText().equals("Digite seu CPF")){
            cpf_func.setText("");
        }
    }//GEN-LAST:event_cpf_funcFocusGained

    private void cpf_funcFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpf_funcFocusLost
        // TODO add your handling code here:
        if(cpf_func.getText().equals("")){
            cpf_func.setText("Digite seu CPF");
        }
    }//GEN-LAST:event_cpf_funcFocusLost

    private void cpf_funcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpf_funcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpf_funcActionPerformed

    private void uniformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uniformeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uniformeActionPerformed

    private void bene_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bene_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bene_nActionPerformed

    private void bene_sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bene_sActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bene_sActionPerformed

    private void nbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbActionPerformed
        // TODO add your handling code here:
        masc.setSelected(false);
        fem.setSelected(false);
    }//GEN-LAST:event_nbActionPerformed

    private void voltar_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar_menuActionPerformed
        // TODO add your handling code here:
        dispose();
        new inicio().setVisible(true);
    }//GEN-LAST:event_voltar_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new funcionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area_func;
    private javax.swing.JRadioButton bene_n;
    private javax.swing.JRadioButton bene_s;
    private javax.swing.JComboBox<String> cargo;
    private javax.swing.JTextField cpf_func;
    private javax.swing.JRadioButton fem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton limpar_func;
    private javax.swing.JRadioButton masc;
    private javax.swing.JRadioButton nb;
    private javax.swing.JLabel news;
    private javax.swing.JTextField nome_func;
    private javax.swing.JButton salvar_func;
    private javax.swing.JCheckBox uniforme;
    private javax.swing.JButton voltar_menu;
    // End of variables declaration//GEN-END:variables
}
