/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.interfacetb;

import javax.swing.JOptionPane;

public class lanche extends javax.swing.JFrame {

    /**
     * Creates new form lanche
     */
    public lanche() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tipo_carne = new javax.swing.JComboBox<>();
        tipo_queijo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        tipo_pao = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        maionese = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        ketchup = new javax.swing.JRadioButton();
        barbecue = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        area_lanche = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        salvar_lanche = new javax.swing.JButton();
        limpar_lanche = new javax.swing.JButton();
        voltar_menu = new javax.swing.JButton();
        nome_lanche = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(161, 146, 134));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\ADS\\interface_chicos_burguer\\interface_chicos-main\\img\\IconBurguerPNG_200x200-removebg-preview.png")); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, -1));

        tipo_carne.setBackground(new java.awt.Color(255, 255, 255));
        tipo_carne.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tipo_carne.setForeground(new java.awt.Color(0, 0, 0));
        tipo_carne.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Costela moída", "Maminha moída", "Cordeiro moído", "Acém moído", " " }));
        tipo_carne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipo_carneActionPerformed(evt);
            }
        });
        jPanel2.add(tipo_carne, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 76, 234, 30));

        tipo_queijo.setBackground(new java.awt.Color(255, 255, 255));
        tipo_queijo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tipo_queijo.setForeground(new java.awt.Color(0, 0, 0));
        tipo_queijo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Cheddar", "Mussarela", "Gouda", "Parmesão", "Inglês" }));
        tipo_queijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipo_queijoActionPerformed(evt);
            }
        });
        jPanel2.add(tipo_queijo, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 164, 282, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Escolha sua carne!");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 42, -1, -1));

        tipo_pao.setBackground(new java.awt.Color(255, 255, 255));
        tipo_pao.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tipo_pao.setForeground(new java.awt.Color(0, 0, 0));
        tipo_pao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Australiano", "Francês redondo", "Brioche", "Com Gergelim" }));
        jPanel2.add(tipo_pao, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 164, 235, 30));
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Escolha seu queijo!");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 136, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Escolha seu Molho!");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Escolha seu pão!");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 136, -1, -1));

        maionese.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        maionese.setForeground(new java.awt.Color(0, 0, 0));
        maionese.setText("Maionese");
        maionese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maioneseActionPerformed(evt);
            }
        });
        jPanel2.add(maionese, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 250, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Nome do Lanche");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 46, -1, -1));

        ketchup.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ketchup.setForeground(new java.awt.Color(0, 0, 0));
        ketchup.setText("Ketchup");
        jPanel2.add(ketchup, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 250, -1, -1));

        barbecue.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        barbecue.setForeground(new java.awt.Color(0, 0, 0));
        barbecue.setText("Barbecue");
        jPanel2.add(barbecue, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 250, -1, -1));

        area_lanche.setBackground(new java.awt.Color(255, 255, 255));
        area_lanche.setColumns(20);
        area_lanche.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        area_lanche.setForeground(new java.awt.Color(0, 0, 0));
        area_lanche.setRows(5);
        jScrollPane1.setViewportView(area_lanche);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 463, 135));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Novo Lanche:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, -1, -1));

        salvar_lanche.setBackground(new java.awt.Color(154, 88, 51));
        salvar_lanche.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        salvar_lanche.setForeground(new java.awt.Color(0, 0, 0));
        salvar_lanche.setText("Salvar");
        salvar_lanche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar_lancheActionPerformed(evt);
            }
        });
        jPanel2.add(salvar_lanche, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 185, 43));

        limpar_lanche.setBackground(new java.awt.Color(154, 88, 51));
        limpar_lanche.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        limpar_lanche.setForeground(new java.awt.Color(0, 0, 0));
        limpar_lanche.setText("Limpar");
        limpar_lanche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpar_lancheActionPerformed(evt);
            }
        });
        jPanel2.add(limpar_lanche, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 185, 42));

        voltar_menu.setBackground(new java.awt.Color(154, 88, 51));
        voltar_menu.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        voltar_menu.setForeground(new java.awt.Color(0, 0, 0));
        voltar_menu.setText("« Voltar Produtos");
        voltar_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar_menuActionPerformed(evt);
            }
        });
        jPanel2.add(voltar_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, 43));

        nome_lanche.setBackground(new java.awt.Color(255, 255, 255));
        nome_lanche.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nome_lanche.setForeground(new java.awt.Color(0, 0, 0));
        nome_lanche.setText("Digite o nome do lanche");
        nome_lanche.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nome_lancheFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nome_lancheFocusLost(evt);
            }
        });
        jPanel2.add(nome_lanche, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 280, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 859, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipo_carneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipo_carneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipo_carneActionPerformed

    private void tipo_queijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipo_queijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipo_queijoActionPerformed

    private void salvar_lancheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar_lancheActionPerformed
        // TODO add your handling code here:
        int valor = JOptionPane.showConfirmDialog(null,"Deseja salvar?","Opções", JOptionPane.YES_NO_CANCEL_OPTION);
        
        if(valor==0){
            lanches l = new lanches();
            l.setNome_lanche(nome_lanche.getText());
            l.setTipo_queijo((String)tipo_queijo.getSelectedItem());
            l.setTipo_carne((String)tipo_carne.getSelectedItem());
            l.setTipo_pao((String)tipo_pao.getSelectedItem());
            if(maionese.isSelected()){
                l.setMolho("Maionese");
            }else if(ketchup.isSelected()){
                l.setMolho("Ketchup");
            }else{
                l.setMolho("Barbecue");
            }
        area_lanche.setText(l.status_lanche());
        }
    }//GEN-LAST:event_salvar_lancheActionPerformed

    private void voltar_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar_menuActionPerformed
        // TODO add your handling code here:
        dispose();
        new carregamento().setVisible(true);
    }//GEN-LAST:event_voltar_menuActionPerformed

    private void maioneseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maioneseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maioneseActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        dispose();
        new inicio().setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void limpar_lancheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpar_lancheActionPerformed
        // TODO add your handling code here:
        nome_lanche.setText("");
        tipo_queijo.setSelectedIndex(0);
        tipo_carne.setSelectedIndex(0);
        tipo_pao.setSelectedIndex(0);
        maionese.setSelected(false);
        ketchup.setSelected(false);
        barbecue.setSelected(false);
        area_lanche.setText("");
        
    }//GEN-LAST:event_limpar_lancheActionPerformed

    private void nome_lancheFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nome_lancheFocusGained
        // TODO add your handling code here:
        if(nome_lanche.getText().equals("Digite o nome do lanche")){
            nome_lanche.setText("");
        }
    }//GEN-LAST:event_nome_lancheFocusGained

    private void nome_lancheFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nome_lancheFocusLost
        // TODO add your handling code here:
        if(nome_lanche.getText().equals("")){
            nome_lanche.setText("Digite o nome do lanche");
        }
    }//GEN-LAST:event_nome_lancheFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lanche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lanche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lanche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lanche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lanche().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area_lanche;
    private javax.swing.JRadioButton barbecue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton ketchup;
    private javax.swing.JButton limpar_lanche;
    private javax.swing.JRadioButton maionese;
    private javax.swing.JTextField nome_lanche;
    private javax.swing.JButton salvar_lanche;
    private javax.swing.JComboBox<String> tipo_carne;
    private javax.swing.JComboBox<String> tipo_pao;
    private javax.swing.JComboBox<String> tipo_queijo;
    private javax.swing.JButton voltar_menu;
    // End of variables declaration//GEN-END:variables
}
