/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.interfacetb;

/**
 *
 * @author 25170628
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        faca_pedido = new javax.swing.JButton();
        cad_produto = new javax.swing.JButton();
        cad_func = new javax.swing.JButton();
        cad_cliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(161, 146, 134));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\ADS\\interface_chicos_burguer\\interface_chicos-main\\img\\IconBurguerPNG_200x200-removebg-preview.png")); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 200, 210));

        faca_pedido.setBackground(new java.awt.Color(154, 88, 51));
        faca_pedido.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        faca_pedido.setForeground(new java.awt.Color(0, 0, 0));
        faca_pedido.setText("Faça seu Pedido!");
        faca_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faca_pedidoActionPerformed(evt);
            }
        });
        jPanel2.add(faca_pedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 260, 60));

        cad_produto.setBackground(new java.awt.Color(154, 88, 51));
        cad_produto.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cad_produto.setForeground(new java.awt.Color(0, 0, 0));
        cad_produto.setText("Cadastre um Produto!");
        cad_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cad_produtoActionPerformed(evt);
            }
        });
        jPanel2.add(cad_produto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 260, 60));

        cad_func.setBackground(new java.awt.Color(154, 88, 51));
        cad_func.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cad_func.setForeground(new java.awt.Color(0, 0, 0));
        cad_func.setText("Cadastro de Funcionario!");
        cad_func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cad_funcActionPerformed(evt);
            }
        });
        jPanel2.add(cad_func, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 260, 60));

        cad_cliente.setBackground(new java.awt.Color(154, 88, 51));
        cad_cliente.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cad_cliente.setForeground(new java.awt.Color(0, 0, 0));
        cad_cliente.setText("Cadastro de Cliente!");
        cad_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cad_clienteActionPerformed(evt);
            }
        });
        jPanel2.add(cad_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 260, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cad_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cad_produtoActionPerformed
        // TODO add your handling code here:
        dispose();
        new produtos().setVisible(true);
    }//GEN-LAST:event_cad_produtoActionPerformed

    private void cad_funcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cad_funcActionPerformed
        // TODO add your handling code here:
        dispose();
        new funcionarios().setVisible(true);
    }//GEN-LAST:event_cad_funcActionPerformed

    private void cad_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cad_clienteActionPerformed
        // TODO add your handling code here:
        dispose();
        new cadastro1().setVisible(true);
    }//GEN-LAST:event_cad_clienteActionPerformed

    private void faca_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faca_pedidoActionPerformed
        // TODO add your handling code here:
        dispose();
        new pedido().setVisible(true);
    }//GEN-LAST:event_faca_pedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cad_cliente;
    private javax.swing.JButton cad_func;
    private javax.swing.JButton cad_produto;
    private javax.swing.JButton faca_pedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
