/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.interfacetb;

import javax.swing.JOptionPane;
        
public class pedido extends javax.swing.JFrame {

    /**
     * Creates new form pedido
     */
    public pedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bebida = new javax.swing.JComboBox<>();
        sobremesa = new javax.swing.JComboBox<>();
        lanche = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        porcao = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        alho_mostarda = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        barbecue = new javax.swing.JRadioButton();
        maionese_verde = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        area_pedido = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        salvar_pedido = new javax.swing.JButton();
        limpar_pedido = new javax.swing.JButton();
        voltar_menu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(161, 146, 134));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\ADS\\interface_chicos_burguer\\interface_chicos-main\\img\\IconBurguerPNG_200x200-removebg-preview.png")); // NOI18N

        bebida.setBackground(new java.awt.Color(255, 255, 255));
        bebida.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bebida.setForeground(new java.awt.Color(0, 0, 0));
        bebida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Água", "Coca-cola", "Pepsi Twist", "Chá de pessêgo", "Suco de morango" }));
        bebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bebidaActionPerformed(evt);
            }
        });

        sobremesa.setBackground(new java.awt.Color(255, 255, 255));
        sobremesa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        sobremesa.setForeground(new java.awt.Color(0, 0, 0));
        sobremesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Croissaint de chocolate", "Bolo de cenoura", "Sorvete de baunilha", "Salada de frutas" }));
        sobremesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobremesaActionPerformed(evt);
            }
        });

        lanche.setBackground(new java.awt.Color(255, 255, 255));
        lanche.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lanche.setForeground(new java.awt.Color(0, 0, 0));
        lanche.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Clássico Chico Smash Burger", "Chicos Bacon Churrasco", "Chicos Salada Master", "Chicos Australiano", "Chicos Frango Brabo", "Chicos Master Fish" }));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Escolha sua Bebida!");

        porcao.setBackground(new java.awt.Color(255, 255, 255));
        porcao.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        porcao.setForeground(new java.awt.Color(0, 0, 0));
        porcao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Chicos Cebola Cabulosa", "Chicos Batata Bolada", "Chicos Dadinhos Maldosos" }));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Escolha sua Sobremesa!");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Escolha seus Molhos!");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Escolha sua Porção!");

        alho_mostarda.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        alho_mostarda.setForeground(new java.awt.Color(0, 0, 0));
        alho_mostarda.setText("Alho e Mostarda");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Escolha seu Lanche!");

        barbecue.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        barbecue.setForeground(new java.awt.Color(0, 0, 0));
        barbecue.setText("Barbecue");

        maionese_verde.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        maionese_verde.setForeground(new java.awt.Color(0, 0, 0));
        maionese_verde.setText("Maionese Verde");

        area_pedido.setBackground(new java.awt.Color(255, 255, 255));
        area_pedido.setColumns(20);
        area_pedido.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        area_pedido.setForeground(new java.awt.Color(0, 0, 0));
        area_pedido.setRows(5);
        jScrollPane1.setViewportView(area_pedido);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Seu pedido:");

        salvar_pedido.setBackground(new java.awt.Color(154, 88, 51));
        salvar_pedido.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        salvar_pedido.setForeground(new java.awt.Color(0, 0, 0));
        salvar_pedido.setText("Salvar");
        salvar_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar_pedidoActionPerformed(evt);
            }
        });

        limpar_pedido.setBackground(new java.awt.Color(154, 88, 51));
        limpar_pedido.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        limpar_pedido.setForeground(new java.awt.Color(0, 0, 0));
        limpar_pedido.setText("Limpar");
        limpar_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpar_pedidoActionPerformed(evt);
            }
        });

        voltar_menu.setBackground(new java.awt.Color(154, 88, 51));
        voltar_menu.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        voltar_menu.setForeground(new java.awt.Color(0, 0, 0));
        voltar_menu.setText("« Voltar Menu");
        voltar_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar_menuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel10))
                            .addComponent(lanche, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(sobremesa, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(bebida, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(porcao, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(salvar_pedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(voltar_menu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(limpar_pedido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(89, 89, 89)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(alho_mostarda)
                                    .addComponent(jLabel11))
                                .addGap(16, 16, 16)
                                .addComponent(barbecue)
                                .addGap(16, 16, 16)
                                .addComponent(maionese_verde))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(8, 8, 8)
                                .addComponent(lanche, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel6)
                                .addGap(0, 0, 0)
                                .addComponent(sobremesa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(8, 8, 8)
                                .addComponent(bebida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel9)
                                .addGap(0, 0, 0)
                                .addComponent(porcao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(12, 12, 12)
                .addComponent(jLabel8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(salvar_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(alho_mostarda)
                                .addGap(5, 5, 5)
                                .addComponent(jLabel11))
                            .addComponent(barbecue)
                            .addComponent(maionese_verde))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(limpar_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(voltar_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sobremesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobremesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sobremesaActionPerformed

    private void bebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bebidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bebidaActionPerformed

    private void voltar_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar_menuActionPerformed
        // TODO add your handling code here:
        dispose();
        new inicio().setVisible(true);
    }//GEN-LAST:event_voltar_menuActionPerformed

    private void salvar_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar_pedidoActionPerformed
        // TODO add your handling code here:
        int valor = JOptionPane.showConfirmDialog(null,"Deseja salvar?","Opções", JOptionPane.YES_NO_CANCEL_OPTION);
        
        if(valor==0){
            pedidoOBJ ped = new pedidoOBJ();
            ped.setLanche_pedido((String)lanche.getSelectedItem());
            ped.setBebida_pedido((String)bebida.getSelectedItem());
            ped.setPorcao_pedido((String)porcao.getSelectedItem());
            ped.setSobremesa_pedido((String)sobremesa.getSelectedItem());
            if(alho_mostarda.isSelected()){
                ped.setMolho_pedido("Alho e Mostarda");
            }else if(barbecue.isSelected()){
                ped.setMolho_pedido("Barbecue");
            }else{
                ped.setMolho_pedido("Maionese Verde");
            }
        area_pedido.setText(ped.status_pedido());
        }
    }//GEN-LAST:event_salvar_pedidoActionPerformed

    private void limpar_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpar_pedidoActionPerformed
        // TODO add your handling code here:
        lanche.setSelectedIndex(0);
        bebida.setSelectedIndex(0);
        porcao.setSelectedIndex(0);
        sobremesa.setSelectedIndex(0);
        maionese_verde.setSelected(false);
        barbecue.setSelected(false);
        alho_mostarda.setSelected(false);
        area_pedido.setText("");
    }//GEN-LAST:event_limpar_pedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton alho_mostarda;
    private javax.swing.JTextArea area_pedido;
    private javax.swing.JRadioButton barbecue;
    private javax.swing.JComboBox<String> bebida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> lanche;
    private javax.swing.JButton limpar_pedido;
    private javax.swing.JRadioButton maionese_verde;
    private javax.swing.JComboBox<String> porcao;
    private javax.swing.JButton salvar_pedido;
    private javax.swing.JComboBox<String> sobremesa;
    private javax.swing.JButton voltar_menu;
    // End of variables declaration//GEN-END:variables
}
