/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.interfacetb;

import javax.swing.JOptionPane;

/**
 *
 * @author pedro
 */
public class porcao extends javax.swing.JFrame {

    /**
     * Creates new form porcao
     */
    public porcao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipo = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tempero = new javax.swing.JComboBox<>();
        base_porcao = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        frito = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        assado = new javax.swing.JRadioButton();
        cozido = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        area_porcao = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        salvar_porcao = new javax.swing.JButton();
        limpar_porcao = new javax.swing.JButton();
        nome_porcao = new javax.swing.JTextField();
        voltar_menu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(161, 146, 134));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\ADS\\interface_chicos_burguer\\interface_chicos-main\\img\\IconBurguerPNG_200x200-removebg-preview.png")); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, -1));

        tempero.setBackground(new java.awt.Color(255, 255, 255));
        tempero.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tempero.setForeground(new java.awt.Color(0, 0, 0));
        tempero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Chili", "Mostarda e mel", "Sal e pimenta", "Paprica e alho", "Alho e limão", "Nenhum" }));
        tempero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temperoActionPerformed(evt);
            }
        });
        jPanel2.add(tempero, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 74, 234, 30));

        base_porcao.setBackground(new java.awt.Color(255, 255, 255));
        base_porcao.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        base_porcao.setForeground(new java.awt.Color(0, 0, 0));
        base_porcao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Batata", "Cebola", "Queijo", "Tapioca", "Massa", "Ovo" }));
        base_porcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                base_porcaoActionPerformed(evt);
            }
        });
        jPanel2.add(base_porcao, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 165, 282, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Escolha o tempero!");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 40, -1, -1));
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Escolha a base!");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 131, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Tipo:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(657, 134, -1, -1));

        tipo.add(frito);
        frito.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        frito.setForeground(new java.awt.Color(0, 0, 0));
        frito.setText("Frito");
        jPanel2.add(frito, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 174, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Nome da Porção!");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 42, -1, -1));

        tipo.add(assado);
        assado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        assado.setForeground(new java.awt.Color(0, 0, 0));
        assado.setText("Assado");
        jPanel2.add(assado, new org.netbeans.lib.awtextra.AbsoluteConstraints(641, 174, -1, -1));

        tipo.add(cozido);
        cozido.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cozido.setForeground(new java.awt.Color(0, 0, 0));
        cozido.setText("Cozido");
        jPanel2.add(cozido, new org.netbeans.lib.awtextra.AbsoluteConstraints(735, 174, -1, -1));

        area_porcao.setBackground(new java.awt.Color(255, 255, 255));
        area_porcao.setColumns(20);
        area_porcao.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        area_porcao.setForeground(new java.awt.Color(0, 0, 0));
        area_porcao.setRows(5);
        jScrollPane1.setViewportView(area_porcao);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 463, 135));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Nova Porção");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, -1, 40));

        salvar_porcao.setBackground(new java.awt.Color(154, 88, 51));
        salvar_porcao.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        salvar_porcao.setForeground(new java.awt.Color(0, 0, 0));
        salvar_porcao.setText("Salvar");
        salvar_porcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar_porcaoActionPerformed(evt);
            }
        });
        jPanel2.add(salvar_porcao, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 185, 43));

        limpar_porcao.setBackground(new java.awt.Color(154, 88, 51));
        limpar_porcao.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        limpar_porcao.setForeground(new java.awt.Color(0, 0, 0));
        limpar_porcao.setText("Limpar");
        limpar_porcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpar_porcaoActionPerformed(evt);
            }
        });
        jPanel2.add(limpar_porcao, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 185, 42));

        nome_porcao.setBackground(new java.awt.Color(255, 255, 255));
        nome_porcao.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nome_porcao.setForeground(new java.awt.Color(0, 0, 0));
        nome_porcao.setText("Digite o nome da porção");
        nome_porcao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nome_porcaoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nome_porcaoFocusLost(evt);
            }
        });
        jPanel2.add(nome_porcao, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 76, 282, -1));

        voltar_menu.setBackground(new java.awt.Color(154, 88, 51));
        voltar_menu.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        voltar_menu.setForeground(new java.awt.Color(0, 0, 0));
        voltar_menu.setText("« Voltar Produtos");
        voltar_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar_menuActionPerformed(evt);
            }
        });
        jPanel2.add(voltar_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, 43));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void temperoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temperoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temperoActionPerformed

    private void base_porcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_base_porcaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_base_porcaoActionPerformed

    private void salvar_porcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar_porcaoActionPerformed
        // TODO add your handling code here:
        int valor = JOptionPane.showConfirmDialog(null, "Deseja Salvar?", "Opções", JOptionPane.YES_NO_CANCEL_OPTION);
        
        if(valor == 0){
            porcaoOBJ p = new porcaoOBJ();
            p.setNome_porcao(nome_porcao.getText());
            p.setBase((String)base_porcao.getSelectedItem());
            p.setTempero((String)tempero.getSelectedItem());
            if(frito.isSelected()){
                p.setTipo("Frito");
            }else if(assado.isSelected()){
                p.setTipo("Assado");
            }else{
                p.setTipo("Cozido");
            }
        area_porcao.setText(p.status_porcao());
        }else if(valor==2){
            System.exit(0);
        }

        
    }//GEN-LAST:event_salvar_porcaoActionPerformed

    private void voltar_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar_menuActionPerformed
        // TODO add your handling code here:
        dispose();
        new carregamento().setVisible(true);
    }//GEN-LAST:event_voltar_menuActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        dispose();
        new inicio().setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void limpar_porcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpar_porcaoActionPerformed
        // TODO add your handling code here:
        nome_porcao.setText("");
        tempero.setSelectedIndex(0);
        base_porcao.setSelectedIndex(0);
        frito.setSelected(false);
        assado.setSelected(false);
        cozido.setSelected(false);
        area_porcao.setText("");
    }//GEN-LAST:event_limpar_porcaoActionPerformed

    private void nome_porcaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nome_porcaoFocusGained
        // TODO add your handling code here:
        if(nome_porcao.getText().equals("Digite o nome da porção")){
            nome_porcao.setText("");
        }
    }//GEN-LAST:event_nome_porcaoFocusGained

    private void nome_porcaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nome_porcaoFocusLost
        // TODO add your handling code here:
        if(nome_porcao.getText().equals("")){
            nome_porcao.setText("Digite o nome da porção");
        }
    }//GEN-LAST:event_nome_porcaoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(porcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(porcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(porcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(porcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new porcao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area_porcao;
    private javax.swing.JRadioButton assado;
    private javax.swing.JComboBox<String> base_porcao;
    private javax.swing.JRadioButton cozido;
    private javax.swing.JRadioButton frito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpar_porcao;
    private javax.swing.JTextField nome_porcao;
    private javax.swing.JButton salvar_porcao;
    private javax.swing.JComboBox<String> tempero;
    private javax.swing.ButtonGroup tipo;
    private javax.swing.JButton voltar_menu;
    // End of variables declaration//GEN-END:variables
}
